CREATE PROCEDURE DELETE_QUESTION @QUESTION_ID INT AS
BEGIN

	DECLARE @INDEX INT, @TEST_ID INT;

	SELECT 
		@INDEX = QUESTION.QUESTION_INDEX, 
		@TEST_ID = QUESTION.TEST_ID 
	FROM QUESTION 
	WHERE QUESTION.ID = @QUESTION_ID;
	
	DELETE 
		QUESTION 
	WHERE 
		QUESTION.ID = @QUESTION_ID;

	UPDATE 
		QUESTION 
	SET 
		QUESTION_INDEX = QUESTION_INDEX - 1 
	WHERE QUESTION.TEST_ID = @TEST_ID AND QUESTION.QUESTION_INDEX > @INDEX;

END